#!/bin/sh
#
# iptables down
#
# === this script should be placed /etc/network/if-post-down.d ===
#
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/sbin:/usr/sbin
export PATH

IPTABLES=/sbin/iptables


# clear
${IPTABLES} -F
${IPTABLES} -F -t nat
${IPTABLES} -X
${IPTABLES} -Z

# policy
${IPTABLES} -P INPUT ACCEPT
${IPTABLES} -P OUTPUT ACCEPT
${IPTABLES} -P FORWARD ACCEPT

