#!/bin/sh
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/sbin:/usr/sbin
export PATH

sleep 3
exec 2>&1

## LocalForward
#exec ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=20 -o ServerAliveCountMax=3 \
#-N -g -L 5900:192.168.1.100:5900 example.com -l user -i "`dirname ${0}`/id_rsa"

## RemoteForward
#exec ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=20 -o ServerAliveCountMax=3 \
#-N -R 8022:127.0.0.1:22 example.com -l user -i "`dirname ${0}`/id_rsa"

## DynamicForward
#exec ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=20 -o ServerAliveCountMax=3 \
#-N -D 1080 example.com -l user -i "`dirname ${0}`/id_rsa"

